services:
  web:
    # Dev: serve your working tree live
    image: nginx:1.27-alpine
    container_name: tpq-web
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # hot-reload is just your browser refresh; files are bind-mounted

  prod:
    # Prod: build a static image (no bind mount)
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tpq-prod
    ports:
      - "${PORT:-8080}:80"
    profiles: ["prod"]  # run with: docker compose --profile prod up --build -d

